name: Java CI with Maven and Email Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run tests
        run: mvn clean test

      - name: Upload Extent Report artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Extent-Report
          path: test-output/extent-report/ExtentReport.html

      - name: Send Email with Extent Report
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "✅ CI Test Report - ${{ github.repository }}"
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
          secure: true
          attachments: test-output/ExtentReport.html
          body: |
            Hello,

            Please find attached the Extent Test Report generated by the CI pipeline.

            • Repo: ${{ github.repository }}
            • Branch: ${{ github.ref_name }}
            • Commit: ${{ github.sha }}
            • Triggered by: ${{ github.actor }}

            Regards,
            GitHub Actions CI
